// All available skills for Delta Green Character Creator

export const ALL_SKILLS = {
    "accounting":     { base: 10, nameKey: "skill_accounting_name", descKey: "skill_accounting_desc" },
    "alertness":      { base: 20, nameKey: "skill_alertness_name", descKey: "skill_alertness_desc" },
    "anthropology":   { base: 0,  nameKey: "skill_anthropology_name", descKey: "skill_anthropology_desc" },
    "archeology":     { base: 0,  nameKey: "skill_archeology_name", descKey: "skill_archeology_desc" },
    "art":            { base: 0,  nameKey: "skill_art_name", descKey: "skill_art_desc", type: true },
    "artillery":      { base: 0,  nameKey: "skill_artillery_name", descKey: "skill_artillery_desc" },
    "athletics":      { base: 30, nameKey: "skill_athletics_name", descKey: "skill_athletics_desc" },
    "bureaucracy":    { base: 10, nameKey: "skill_bureaucracy_name", descKey: "skill_bureaucracy_desc" },
    "computer_science":{ base: 0, nameKey: "skill_computer_science_name", descKey: "skill_computer_science_desc" },
    "craft":          { base: 0,  nameKey: "skill_craft_name", descKey: "skill_craft_desc", type: true },
    "criminology":    { base: 10, nameKey: "skill_criminology_name", descKey: "skill_criminology_desc" },
    "demolitions":    { base: 0,  nameKey: "skill_demolitions_name", descKey: "skill_demolitions_desc" },
    "disguise":       { base: 10, nameKey: "skill_disguise_name", descKey: "skill_disguise_desc" },
    "dodge":          { base: 30, nameKey: "skill_dodge_name", descKey: "skill_dodge_desc" },
    "drive":          { base: 20, nameKey: "skill_drive_name", descKey: "skill_drive_desc" },
    "firearms":       { base: 20, nameKey: "skill_firearms_name", descKey: "skill_firearms_desc" },
    "first_aid":      { base: 10, nameKey: "skill_first_aid_name", descKey: "skill_first_aid_desc" },
    "foreign_language":{ base: 0, nameKey: "skill_foreign_language_name", descKey: "skill_foreign_language_desc", type: true },
    "forensics":      { base: 0,  nameKey: "skill_forensics_name", descKey: "skill_forensics_desc" },
    "heavy_machinery":{ base: 10, nameKey: "skill_heavy_machinery_name", descKey: "skill_heavy_machinery_desc" },
    "heavy_weapons":  { base: 0,  nameKey: "skill_heavy_weapons_name", descKey: "skill_heavy_weapons_desc" },
    "history":        { base: 10, nameKey: "skill_history_name", descKey: "skill_history_desc" },
    "humint":         { base: 10, nameKey: "skill_humint_name", descKey: "skill_humint_desc" },
    "law":            { base: 0,  nameKey: "skill_law_name", descKey: "skill_law_desc" },
    "medicine":       { base: 0,  nameKey: "skill_medicine_name", descKey: "skill_medicine_desc" },
    "melee_weapons":  { base: 30, nameKey: "skill_melee_weapons_name", descKey: "skill_melee_weapons_desc" },
    "military_science":{ base: 0, nameKey: "skill_military_science_name", descKey: "skill_military_science_desc", type: true },
    "navigate":       { base: 10, nameKey: "skill_navigate_name", descKey: "skill_navigate_desc" },
    "occult":         { base: 10, nameKey: "skill_occult_name", descKey: "skill_occult_desc" },
    "persuade":       { base: 20, nameKey: "skill_persuade_name", descKey: "skill_persuade_desc" },
    "pharmacy":       { base: 0,  nameKey: "skill_pharmacy_name", descKey: "skill_pharmacy_desc" },
    "pilot":          { base: 0,  nameKey: "skill_pilot_name", descKey: "skill_pilot_desc", type: true },
    "psychotherapy":  { base: 10, nameKey: "skill_psychotherapy_name", descKey: "skill_psychotherapy_desc" },
    "ride":           { base: 10, nameKey: "skill_ride_name", descKey: "skill_ride_desc" },
    "science":        { base: 0,  nameKey: "skill_science_name", descKey: "skill_science_desc", type: true },
    "search":         { base: 20, nameKey: "skill_search_name", descKey: "skill_search_desc" },
    "sigint":         { base: 0,  nameKey: "skill_sigint_name", descKey: "skill_sigint_desc" },
    "stealth":        { base: 10, nameKey: "skill_stealth_name", descKey: "skill_stealth_desc" },
    "surgery":        { base: 0,  nameKey: "skill_surgery_name", descKey: "skill_surgery_desc" },
    "survival":       { base: 10, nameKey: "skill_survival_name", descKey: "skill_survival_desc" },
    "swim":           { base: 20, nameKey: "skill_swim_name", descKey: "skill_swim_desc" },
    "unarmed_combat": { base: 40, nameKey: "skill_unarmed_combat_name", descKey: "skill_unarmed_combat_desc" },
    "unnatural":      { base: 0,  nameKey: "skill_unnatural_name", descKey: "skill_unnatural_desc" }
};

